import Head from "next/head";
import Image from "next/image";
import Footer from "../components/footer";
import Navbar, { PAGE_HOME } from "../components/navbar";
import profilePic from "../public/profile/profile1.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar location={PAGE_HOME} />
      <div className="sm:container sm:mx-auto">
        <div className="text-md m-4">
          Hello, wecome to Richard{"'"}s website!
        </div>
        <Image
          src={profilePic}
          alt="Richard Kennedy profile"
          layout="responsive"
        />
      </div>
      <Footer />
    </div>
  );
}
